"""create_incidents_and_media

Revision ID: 004_incidents_media
Revises: 003_admin_facilities
Create Date: 2026-09-15 15:13:05.478529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '004_incidents_media'
down_revision: Union[str, None] = '003_admin_facilities'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waste_categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_severity', sa.String(length=20), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('color_hex', sa.String(length=10), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_table('incidents',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('tracking_code', sa.String(length=30), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address_text', sa.String(length=500), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('masked_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estimated_volume_m3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('reporter_phone_masked', sa.String(length=20), nullable=True),
    sa.Column('upvotes_count', sa.Integer(), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['waste_categories.category_id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['administrative_units.unit_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('incident_id'),
    sa.UniqueConstraint('tracking_code')
    )
    op.create_table('incident_comments',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['incident_comments.comment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('incident_media',
    sa.Column('media_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('exif_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('exif_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('exif_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_tampered_warning', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_table('incident_status_history',
    sa.Column('history_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('incident_transfers',
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('from_unit_id', sa.Integer(), nullable=False),
    sa.Column('to_unit_id', sa.Integer(), nullable=False),
    sa.Column('transferred_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('escalation_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_unit_id'], ['administrative_units.unit_id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_unit_id'], ['administrative_units.unit_id'], ),
    sa.ForeignKeyConstraint(['transferred_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_transfers')
    op.drop_table('incident_status_history')
    op.drop_table('incident_media')
    op.drop_table('incident_comments')
    op.drop_table('incidents')
    op.drop_table('waste_categories')
    # ### end Alembic commands ###

