"""create_monitoring_sla_audit

Revision ID: 006_monitoring_sla
Revises: 005_dispatch_verify
Create Date: 2026-09-15 15:13:06.452114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '006_monitoring_sla'
down_revision: Union[str, None] = '005_dispatch_verify'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_policies',
    sa.Column('policy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('response_time_hours', sa.Integer(), nullable=False),
    sa.Column('resolution_time_hours', sa.Integer(), nullable=False),
    sa.Column('warning_threshold_percentage', sa.Integer(), nullable=False),
    sa.Column('penalty_points_per_hour', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['waste_categories.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_uri', sa.String(length=500), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('kpi_evaluations',
    sa.Column('evaluation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_month', sa.Integer(), nullable=False),
    sa.Column('evaluation_year', sa.Integer(), nullable=False),
    sa.Column('total_assigned', sa.Integer(), nullable=False),
    sa.Column('completed_on_time', sa.Integer(), nullable=False),
    sa.Column('completed_overdue', sa.Integer(), nullable=False),
    sa.Column('sla_compliance_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('average_cleanliness_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('penalty_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('bonus_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_kpi_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rank_grade', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['work_teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['administrative_units.unit_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_evaluations')
    op.drop_table('audit_logs')
    op.drop_table('sla_policies')
    # ### end Alembic commands ###

