"""create_spatial_webgis_advanced

Revision ID: 007_spatial_webgis
Revises: 006_monitoring_sla
Create Date: 2026-09-15 15:13:06.945977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '007_spatial_webgis'
down_revision: Union[str, None] = '006_monitoring_sla'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flood_zones_monitoring',
    sa.Column('zone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_name', sa.String(length=200), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('rainfall_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('flood_depth_cm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('blocked_drainage_points_count', sa.Integer(), nullable=False),
    sa.Column('is_actively_flooded', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['administrative_units.unit_id'], ),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('incident_clusters_hotspots',
    sa.Column('cluster_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('cluster_type', sa.String(length=30), nullable=False),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('average_risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dominant_waste_category_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dominant_waste_category_id'], ['waste_categories.category_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['administrative_units.unit_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_table('safe_routes_cache',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('origin_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('destination_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('fastest_route_geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('fastest_distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fastest_duration_mins', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fastest_risk_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('safest_route_geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('safest_distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('safest_duration_mins', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('safest_risk_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hazards_avoided_count', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('user_map_favorites',
    sa.Column('favorite_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('filter_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('viewport_center', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('zoom_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.create_table('user_watch_areas',
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('area_name', sa.String(length=150), nullable=False),
    sa.Column('center_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('geofence_polygon', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('notify_push', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_watch_areas')
    op.drop_table('user_map_favorites')
    op.drop_table('safe_routes_cache')
    op.drop_table('incident_clusters_hotspots')
    op.drop_table('flood_zones_monitoring')
    # ### end Alembic commands ###

