"""create_ai_smart_analytics

Revision ID: 008_ai_analytics
Revises: 007_spatial_webgis
Create Date: 2026-09-15 15:13:07.615239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '008_ai_analytics'
down_revision: Union[str, None] = '007_spatial_webgis'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_knowledge_embeddings',
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('document_title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('knowledge_id')
    )
    op.create_table('ai_duplicate_groups',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('primary_incident_id', sa.UUID(), nullable=False),
    sa.Column('duplicate_incident_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('spatial_distance_meters', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('time_delta_minutes', sa.Integer(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_confirmed_by_officer', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('ai_incident_summaries',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('ai_executive_summary', sa.Text(), nullable=False),
    sa.Column('key_environmental_threats', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('suggested_priority', sa.String(length=20), nullable=True),
    sa.Column('recommended_equipment', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('estimated_cleanup_time_hours', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_table('ai_analysis_results',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('detected_classes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('bounding_boxes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_volume_m3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('suggested_severity', sa.String(length=20), nullable=True),
    sa.Column('suggested_category_id', sa.Integer(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['incident_media.media_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['waste_categories.category_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_analysis_results')
    op.drop_table('ai_incident_summaries')
    op.drop_table('ai_duplicate_groups')
    op.drop_table('ai_knowledge_embeddings')
    # ### end Alembic commands ###

