"""create_advanced_iot_fleet_legal

Revision ID: 011_iot_fleet_legal
Revises: 010_system_reports
Create Date: 2026-09-15 15:13:09.645796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '011_iot_fleet_legal'
down_revision: Union[str, None] = '010_system_reports'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalty_regulations',
    sa.Column('regulation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decree_reference', sa.String(length=100), nullable=False),
    sa.Column('article_clause', sa.String(length=50), nullable=False),
    sa.Column('violation_behavior', sa.Text(), nullable=False),
    sa.Column('min_fine_vnd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_fine_vnd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remedial_measures', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('regulation_id')
    )
    op.create_table('iot_sensor_stations',
    sa.Column('station_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_code', sa.String(length=50), nullable=False),
    sa.Column('station_name', sa.String(length=150), nullable=False),
    sa.Column('station_type', sa.String(length=50), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=False),
    sa.Column('battery_powered', sa.Boolean(), nullable=False),
    sa.Column('solar_powered', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['administrative_units.unit_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('station_id'),
    sa.UniqueConstraint('station_code')
    )
    op.create_table('iot_sensor_alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(length=50), nullable=False),
    sa.Column('measured_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('threshold_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qcvn_standard', sa.String(length=50), nullable=False),
    sa.Column('alert_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['iot_sensor_stations.station_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('iot_sensor_telemetry',
    sa.Column('telemetry_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('aqi_index', sa.Integer(), nullable=True),
    sa.Column('pm2_5', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pm10', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('co2_ppm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('temperature_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('humidity_percent', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('water_level_cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('water_ph', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('dissolved_oxygen_mg_l', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['iot_sensor_stations.station_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('telemetry_id')
    )
    op.create_table('vehicle_fuel_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('start_odometer_km', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('end_odometer_km', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('distance_traveled_km', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('fuel_liters_added', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fuel_cost_vnd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['work_teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('violation_records',
    sa.Column('record_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('record_code', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('regulation_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('offender_name', sa.String(length=150), nullable=True),
    sa.Column('offender_id_card', sa.String(length=20), nullable=True),
    sa.Column('offender_vehicle_plate', sa.String(length=30), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('fine_amount_vnd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING_PAYMENT'"), nullable=False),
    sa.Column('evidence_media_urls', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('payment_deadline', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['regulation_id'], ['penalty_regulations.regulation_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['administrative_units.unit_id'], ),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('record_code')
    )
    op.create_table('waste_collection_routes',
    sa.Column('route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_code', sa.String(length=50), nullable=False),
    sa.Column('route_name', sa.String(length=150), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('assigned_team_id', sa.Integer(), nullable=True),
    sa.Column('route_path', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('operating_days', sa.String(length=50), nullable=False),
    sa.Column('start_time_scheduled', sa.Time(), nullable=False),
    sa.Column('end_time_scheduled', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_team_id'], ['work_teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['administrative_units.unit_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('route_id'),
    sa.UniqueConstraint('route_code')
    )
    op.create_table('route_checkpoints',
    sa.Column('checkpoint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_name', sa.String(length=150), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('expected_arrival_time', sa.Time(), nullable=True),
    sa.Column('expected_waste_volume_m3', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('stop_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['waste_collection_routes.route_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_checkpoints')
    op.drop_table('waste_collection_routes')
    op.drop_table('violation_records')
    op.drop_table('vehicle_fuel_logs')
    op.drop_table('iot_sensor_telemetry')
    op.drop_table('iot_sensor_alerts')
    op.drop_table('iot_sensor_stations')
    op.drop_table('penalty_regulations')
    # ### end Alembic commands ###

